### ISSUE TITLE
Change the project name to Shi Shuo Xin Yu

### ISSUE THREAD

**Issue by K0u1e** [Sh-Zh-7/BBKing-sjx#1]
It's recommended to change the project name to Shi Shuo Xin Yu.

**Comment by Sh-Zh-7** [comment]
（用中文交流吧，老外也不看这东西

**Comment by Sh-Zh-7** [comment]
英文部分暂时保留BBKing(仓库名称/域名)，其余所有涉及BBKing的中文翻译/引用都改成「世说鑫语」。
说人话：BBKing-sjx的中文翻译改成「世说鑫语」。
